export const industries = [
  "Information and Communications Technology (ICT)",
  "Business, Management, and Entrepreneurship",
  "Finance, Banking, and Accounting",
  "Human Resources and Organizational Development",
  "Sales, Marketing, and Customer Service",
  "Education and Teacher Development",
  "Healthcare and Allied Health",
  "Pharmacy and Pharmaceutical Services",
  "Dental and Oral Healthcare",
  "Mental Health, Psychology, and Counseling",
  "Social Work and Community Development",
  "Engineering",
  "Architecture, Interior Design, and Environmental Planning",
  "Construction and Skilled Trades",
  "Manufacturing and Industrial Technology",
  "Automotive and Land Transportation",
  "Aviation and Aerospace",
  "Maritime, Seafaring, and Ship Operations",
  "Logistics, Supply Chain, and Customs Administration",
  "Agriculture, Agribusiness, and Food Production",
  "Fisheries and Aquaculture",
  "Forestry, Environment, and Natural Resources",
  "Science, Laboratory, and Research",
  "Chemistry and Chemical Technology",
  "Energy, Electrical Power, and Utilities",
  "Real Estate, Property Management, and Appraisal",
  "Law, Legal Studies, and Paralegal Services",
  "Government, Public Administration, and Civil Service",
  "Criminology, Law Enforcement, and Public Safety",
  "Security and Protective Services",
  "Disaster Risk Reduction and Emergency Services",
  "Hospitality, Tourism, and Travel Services",
  "Culinary Arts, Baking, and Food Services",
  "Beauty, Wellness, and Personal Care",
  "Creative Arts, Design, and Multimedia",
  "Media, Broadcasting, and Communication",
  "Language, Translation, and Communication Skills",
  "Retail, Merchandising, and E-Commerce",
  "Business Process Outsourcing (BPO) and Contact Center Services",
  "Data Analytics, Artificial Intelligence, and Cybersecurity",
  "Sports, Fitness, and Recreation",
  "Religious and Ministry Studies",
  "Other",
]
